<?php
/**
 * GET  /api/get_db_config.php  → Return current config (password masked)
 * POST /api/get_db_config.php  → Save new config + test connection first
 */

error_reporting(0);
ini_set('display_errors', '0');

// ── Security: only allow local / trusted origins ───────────────────────────
$allowedHosts = ['localhost', '127.0.0.1', '::1'];
$requestHost  = $_SERVER['HTTP_HOST'] ?? '';
$remoteAddr   = $_SERVER['REMOTE_ADDR'] ?? '';

if (!in_array(strtolower(explode(':', $requestHost)[0]), $allowedHosts, true)
    && !in_array($remoteAddr, $allowedHosts, true)) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'Access denied']);
    exit;
}

header('Content-Type: application/json; charset=utf-8');

// ── Config file path (outside public webroot when possible) ────────────────
// Stores config in /config/db.env  (same dir as database.php but .env extension)
$configFile = __DIR__ . '/../config/db.env';

// ── Helper: parse .env file → associative array ────────────────────────────
function parseEnvFile(string $path): array {
    $defaults = [
        'DB_HOST'    => 'localhost',
        'DB_PORT'    => '3306',
        'DB_NAME'    => 'db_phacoreport',
        'DB_USER'    => 'root',
        'DB_PASS'    => '',
        'DB_CHARSET' => 'utf8mb4',
    ];
    if (!file_exists($path)) return $defaults;

    $lines  = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $result = $defaults;
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || strpos($line, '#') === 0) continue;
        if (strpos($line, '=') === false) continue;
        [$key, $val] = explode('=', $line, 2);
        $key = trim($key);
        $val = trim($val, " \t\n\r\0\x0B\"'"); // strip optional quotes
        if (array_key_exists($key, $result)) {
            $result[$key] = $val;
        }
    }
    return $result;
}

// ── Helper: write config to .env file ─────────────────────────────────────
function writeEnvFile(string $path, array $config): bool {
    $lines = [
        '# Phaco Report – Database Configuration',
        '# Auto-generated by settings page. Do NOT commit this file.',
        '# Keep this file outside public webroot in production.',
        '',
        'DB_HOST='    . $config['DB_HOST'],
        'DB_PORT='    . $config['DB_PORT'],
        'DB_NAME='    . $config['DB_NAME'],
        'DB_USER='    . $config['DB_USER'],
        'DB_PASS='    . $config['DB_PASS'],
        'DB_CHARSET=' . ($config['DB_CHARSET'] ?? 'utf8mb4'),
    ];
    $written = file_put_contents($path, implode("\n", $lines) . "\n", LOCK_EX);
    return $written !== false;
}

// ── Helper: test connection with given params ──────────────────────────────
function testConnection(array $cfg): array {
    try {
        $dsn = sprintf(
            'mysql:host=%s;port=%s;dbname=%s;charset=%s',
            $cfg['DB_HOST'],
            $cfg['DB_PORT'],
            $cfg['DB_NAME'],
            $cfg['DB_CHARSET'] ?? 'utf8mb4'
        );
        $pdo = new PDO($dsn, $cfg['DB_USER'], $cfg['DB_PASS'], [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_TIMEOUT            => 5,
        ]);
        // Quick sanity query
        $row = $pdo->query("SELECT VERSION() AS ver")->fetch();
        return ['ok' => true, 'version' => $row['ver'] ?? ''];
    } catch (PDOException $e) {
        return ['ok' => false, 'error' => $e->getMessage()];
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  GET → return current config (password masked)
// ═══════════════════════════════════════════════════════════════════════════
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $cfg = parseEnvFile($configFile);

    // Test current connection status
    $conn = testConnection($cfg);

    echo json_encode([
        'success'  => true,
        'config'   => [
            'DB_HOST'    => $cfg['DB_HOST'],
            'DB_PORT'    => $cfg['DB_PORT'],
            'DB_NAME'    => $cfg['DB_NAME'],
            'DB_USER'    => $cfg['DB_USER'],
            'DB_PASS'    => str_repeat('•', min(strlen($cfg['DB_PASS']), 12)), // masked
            'DB_CHARSET' => $cfg['DB_CHARSET'],
        ],
        'connection' => $conn,
    ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    exit;
}

// ═══════════════════════════════════════════════════════════════════════════
//  POST → validate → test → save
// ═══════════════════════════════════════════════════════════════════════════
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $raw  = file_get_contents('php://input');
    $body = json_decode($raw, true);
    if (!is_array($body)) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Invalid JSON body']);
        exit;
    }

    // Load existing config (so we can keep the old password if blank was sent)
    $current = parseEnvFile($configFile);

    $newCfg = [
        'DB_HOST'    => trim($body['DB_HOST']    ?? $current['DB_HOST']),
        'DB_PORT'    => trim($body['DB_PORT']    ?? $current['DB_PORT']),
        'DB_NAME'    => trim($body['DB_NAME']    ?? $current['DB_NAME']),
        'DB_USER'    => trim($body['DB_USER']    ?? $current['DB_USER']),
        // If the UI sent blank or masked dots → keep existing password
        'DB_PASS'    => (isset($body['DB_PASS']) && trim($body['DB_PASS']) !== ''
                         && strpos($body['DB_PASS'], '•') === false)
                         ? trim($body['DB_PASS'])
                         : $current['DB_PASS'],
        'DB_CHARSET' => trim($body['DB_CHARSET'] ?? $current['DB_CHARSET'] ?? 'utf8mb4'),
    ];

    // Validate required fields
    foreach (['DB_HOST', 'DB_NAME', 'DB_USER'] as $req) {
        if (empty($newCfg[$req])) {
            http_response_code(422);
            echo json_encode(['success' => false, 'message' => "Field {$req} is required"]);
            exit;
        }
    }

    // Test connection BEFORE saving
    $test = testConnection($newCfg);
    if (!$test['ok']) {
        http_response_code(422);
        echo json_encode([
            'success' => false,
            'message' => 'ไม่สามารถเชื่อมต่อฐานข้อมูลได้: ' . $test['error'],
        ], JSON_UNESCAPED_UNICODE);
        exit;
    }

    // Save to .env file
    if (!writeEnvFile($configFile, $newCfg)) {
        http_response_code(500);
        echo json_encode(['success' => false, 'message' => 'ไม่สามารถบันทึกไฟล์ config ได้ (ตรวจสอบสิทธิ์การเขียน)'], JSON_UNESCAPED_UNICODE);
        exit;
    }

    // Also regenerate database.php so PHP app picks up new values immediately
    $dbPhpContent = <<<PHP
<?php
/**
 * Database Connection Configuration – Phaco Report
 * ⚠  Auto-generated from config/db.env – Do NOT edit manually.
 *    Use the Settings page to change connection parameters.
 */

\$_dbEnv = parse_ini_file(__DIR__ . '/db.env');

define('DB_HOST',    \$_dbEnv['DB_HOST']    ?? 'localhost');
define('DB_PORT',    \$_dbEnv['DB_PORT']    ?? '3306');
define('DB_NAME',    \$_dbEnv['DB_NAME']    ?? 'db_phacoreport');
define('DB_USER',    \$_dbEnv['DB_USER']    ?? 'root');
define('DB_PASS',    \$_dbEnv['DB_PASS']    ?? '');
define('DB_CHARSET', \$_dbEnv['DB_CHARSET'] ?? 'utf8mb4');

function getDbConnection() {
    static \$pdo = null;
    if (\$pdo === null) {
        try {
            \$dsn = sprintf(
                "mysql:host=%s;port=%s;dbname=%s;charset=%s",
                DB_HOST, DB_PORT, DB_NAME, DB_CHARSET
            );
            \$options = [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ];
            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
            \$pdo->exec("SET time_zone = '+07:00'");
            \$pdo->exec("SET NAMES utf8mb4");
        } catch (PDOException \$e) {
            http_response_code(500);
            echo json_encode([
                'success' => false,
                'message' => 'Database connection failed: ' . \$e->getMessage()
            ], JSON_UNESCAPED_UNICODE);
            exit;
        }
    }
    return \$pdo;
}

function sendJsonResponse(\$data, \$statusCode = 200) {
    http_response_code(\$statusCode);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(\$data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    exit;
}
PHP;

    // Save/Log config history to Database Table `db_config_history`
    try {
        $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s', $newCfg['DB_HOST'], $newCfg['DB_PORT'], $newCfg['DB_NAME'], $newCfg['DB_CHARSET'] ?? 'utf8mb4');
        $dbPdo = new PDO($dsn, $newCfg['DB_USER'], $newCfg['DB_PASS'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        
        // Auto-create history table if not exists
        $dbPdo->exec("CREATE TABLE IF NOT EXISTS `db_config_history` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `db_host` VARCHAR(255) NOT NULL,
            `db_port` VARCHAR(10) NOT NULL,
            `db_name` VARCHAR(100) NOT NULL,
            `db_user` VARCHAR(100) NOT NULL,
            `db_charset` VARCHAR(50) DEFAULT 'utf8mb4',
            `updated_by` VARCHAR(100) DEFAULT 'system_admin',
            `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");
        
        $stmtHist = $dbPdo->prepare("INSERT INTO `db_config_history` (db_host, db_port, db_name, db_user, db_charset, updated_at) VALUES (?, ?, ?, ?, ?, NOW())");
        $stmtHist->execute([$newCfg['DB_HOST'], $newCfg['DB_PORT'], $newCfg['DB_NAME'], $newCfg['DB_USER'], $newCfg['DB_CHARSET'] ?? 'utf8mb4']);
    } catch (Exception $e) {
        // Table logging fallback (continue saving even if history table write fails)
    }

    echo json_encode([
        'success'  => true,
        'message'  => 'บันทึก Database Config ลงฐานข้อมูลสำเร็จ (' . $test['version'] . ')',
        'version'  => $test['version'],
    ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    exit;
}

// Method not allowed
http_response_code(405);
echo json_encode(['success' => false, 'message' => 'Method not allowed']);
